name: format

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    shell: bash

jobs:
  clang-format:
    name: clang-format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install GitPython

    - name: Check formatting
      run: python tools/ntl format check
