name: tidy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    shell: bash

jobs:
  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: latest
        ninjaVersion: latest

    - name: Install dependencies
      run: pip install GitPython

    - name: Analyze code
      run: python tools/ntl tidy
